"""
Django settings for drf project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta


BASE_DIR = Path(__file__).resolve().parent.parent

env_paths = [
    BASE_DIR.parent.parent / '.env',
    Path('/usr/app/.env'),
    BASE_DIR / '.env',
    Path('.env'),
]

for env_path in env_paths:
    if env_path.exists():
        load_dotenv(dotenv_path=env_path)
        break
else:
    load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vb4%^*#9#k_m5iy=2k!9u$=8kz1nb(ijjntx5mqm#m&cnrv_nq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'habit-api', 'host.docker.internal', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt',

    'auth_user.apps.AuthUserConfig',
    'habit.apps.HabitConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'postgres_db'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    # ===============================
    # РЕНДЕРЕРЫ (как возвращаются данные)
    # ===============================

    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # JSON формат (основной)
        'rest_framework.renderers.BrowsableAPIRenderer',
        # Веб-интерфейс DRF (убрать в продакшене)
        # 'rest_framework.renderers.TemplateHTMLRenderer', # HTML шаблоны
        # 'rest_framework.renderers.StaticHTMLRenderer',   # Статический HTML
        # 'rest_framework.renderers.XMLRenderer',          # XML формат
    ],

    # ===============================
    # ПАРСЕРЫ (как принимаются данные)
    # ===============================

    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',  # JSON данные (основной)
        'rest_framework.parsers.FormParser',  # HTML формы
        'rest_framework.parsers.MultiPartParser',  # Файлы и формы
        # 'rest_framework.parsers.FileUploadParser', # Только файлы
        # 'rest_framework.parsers.XMLParser',        # XML данные
    ],

    # ===============================
    # АУТЕНТИФИКАЦИЯ (кто это)
    # ===============================

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    # ===============================
    # ПРАВА ДОСТУПА (что можно делать)
    # ===============================

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        # Только аутентифицированные
        # 'rest_framework.permissions.AllowAny',                    # Все могут
        # 'rest_framework.permissions.IsAuthenticatedOrReadOnly',   # Чтение всем, запись авторизованным
        # 'rest_framework.permissions.IsAdminUser',                 # Только админы
    ],

    # ===============================
    # THROTTLING (ограничение запросов)
    # ===============================

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        # Для анонимных пользователей
        'rest_framework.throttling.UserRateThrottle',
        # Для авторизованных пользователей
        # 'rest_framework.throttling.ScopedRateThrottle', # По scope'ам
    ],

    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',  # Анонимы: 100 запросов в час
        'user': '1000/m',  # Пользователи: 1000 запросов в час
    },

    # ===============================
    # ПАГИНАЦИЯ (разбивка на страницы)
    # ===============================

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,  # Количество объектов на странице по умолчанию

    # Альтернативные классы пагинации:
    # 'rest_framework.pagination.LimitOffsetPagination'  # ?limit=20&offset=40
    # 'rest_framework.pagination.CursorPagination'       # Для больших датасетов

    # ===============================
    # ФИЛЬТРАЦИЯ И ПОИСК
    # ===============================

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # django-filter
        'rest_framework.filters.SearchFilter',  # Поиск по полям
        'rest_framework.filters.OrderingFilter',  # Сортировка
    ],

    # Параметры для фильтрации
    'SEARCH_PARAM': 'search',  # ?search=query
    'ORDERING_PARAM': 'ordering',  # ?ordering=field_name
    'FILTER_PARAM': 'filter',  # Кастомный параметр фильтра

    # ===============================
    # ВЕРСИОНИРОВАНИЕ API
    # ===============================

    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',  # Версия по умолчанию
    'ALLOWED_VERSIONS': ['v1', 'v2'],  # Разрешенные версии
    'VERSION_PARAM': 'version',  # Параметр версии

    # ===============================
    # ОБРАБОТКА ИСКЛЮЧЕНИЙ
    # ===============================

    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',

    # ===============================
    # СХЕМА И ДОКУМЕНТАЦИЯ
    # ===============================

    # 'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',

    # ===============================
    # МЕТАДАННЫЕ (для OPTIONS запросов)
    # ===============================

    'DEFAULT_METADATA_CLASS': 'rest_framework.metadata.SimpleMetadata',

    # ===============================
    # CONTENT NEGOTIATION (выбор формата ответа)
    # ===============================

    'DEFAULT_CONTENT_NEGOTIATION_CLASS': 'rest_framework.negotiation.DefaultContentNegotiation',

    # ===============================
    # ФОРМАТЫ ДАТА/ВРЕМЯ
    # ===============================

    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',  # Формат datetime в ответах
    'DATETIME_INPUT_FORMATS': [  # Принимаемые форматы datetime
        '%Y-%m-%d %H:%M:%S',
        '%Y-%m-%d %H:%M:%S.%f',
        '%Y-%m-%d %H:%M',
        '%Y-%m-%dT%H:%M:%S.%fZ',
        'iso-8601',
    ],

    'DATE_FORMAT': '%Y-%m-%d',  # Формат date в ответах
    'DATE_INPUT_FORMATS': [  # Принимаемые форматы date
        '%Y-%m-%d',
        'iso-8601',
    ],

    'TIME_FORMAT': '%H:%M:%S',  # Формат time в ответах
    'TIME_INPUT_FORMATS': [  # Принимаемые форматы time
        '%H:%M:%S',
        '%H:%M:%S.%f',
        '%H:%M',
    ],

    # ===============================
    # UNICODE И ФОРМАТИРОВАНИЕ JSON
    # ===============================

    'UNICODE_JSON': True,  # Поддержка Unicode в JSON (не escape символы)
    'COMPACT_JSON': False,  # Компактный JSON без отступов (для продакшена True)
    'STRICT_JSON': True,  # Строгий парсинг JSON
    'COERCE_DECIMAL_TO_STRING': True,
    # Decimal как строка (избегает проблем с точностью)

    # ===============================
    # НАСТРОЙКИ ТЕСТИРОВАНИЯ
    # ===============================

    'TEST_REQUEST_DEFAULT_FORMAT': 'json',  # Формат по умолчанию для тестов
    'TEST_REQUEST_RENDERER_CLASSES': [  # Рендереры для тестов
        'rest_framework.renderers.MultiPartRenderer',
        'rest_framework.renderers.JSONRenderer',
    ],

    # ===============================
    # URL PATTERNS
    # ===============================

    'URL_FORMAT_OVERRIDE': 'format',  # ?format=json для выбора формата
    'FORMAT_SUFFIX_KWARG': 'format',  # Ключ для format suffix в URL

    # ===============================
    # BROWSABLE API НАСТРОЙКИ
    # ===============================

    'HTML_SELECT_CUTOFF': 1000,  # Лимит опций в HTML select
    'HTML_SELECT_CUTOFF_TEXT': "More than {count} items...",

    # ===============================
    # ПРОИЗВОДИТЕЛЬНОСТЬ
    # ===============================

    'UPLOADED_FILES_USE_URL': True,  # Использовать URL для загруженных файлов
    'URL_FIELD_NAME': 'url',  # Имя поля для URL в HyperlinkedModelSerializer

    # ===============================
    # БЕЗОПАСНОСТЬ
    # ===============================

    'NUM_PROXIES': None,
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}


AUTH_USER_MODEL = 'auth_user.AuthUser'


CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/0")

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")