# Generated by Django 5.2.8 on 2025-11-14 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('repeat', models.CharField(max_length=50, verbose_name='Переодичность')),
                ('execution_time', models.TimeField(verbose_name='Время выполнения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.CharField(blank=True, default='не сделано', max_length=10, verbose_name='Статус')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='Привычка')),
            ],
            options={
                'verbose_name': 'Журнал привычки',
                'verbose_name_plural': 'Журналы привычек',
                'ordering': ['-habit__created_at'],
            },
        ),
    ]
