# Generated by Django 5.2.8 on 2025-11-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_habit_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['created_at', 'title'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AlterModelOptions(
            name='habitlog',
            options={'ordering': ['habit__created_at'], 'verbose_name': 'Журнал привычки', 'verbose_name_plural': 'Журналы привычек'},
        ),
        migrations.AddField(
            model_name='habitlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.TimeField(verbose_name='Время напоминания'),
        ),
    ]
